/**
 * This file contains all the global constants used across the application
 */

const BASE_URL = "http://localhost:789/";
// const BASE_URL = 'http://10.37.55.104:789/';
// "http://10.37.54.153:789/1.0.0/",
// "https://10.37.55.150:789/1.0.0/", -- My Local IP Path

const GOOGLE_API_KEY = "AIzaSyDfCZ3z5G7md40bRo5SiYTPdAx1PdhYfY8";
// "AIzaSyCxApL0BGCmAkGJxA9L40l6WEAbLQxkTpQ";

const API = {
  GET_MANAGE_BOOKING: "manageBooking/getManageBooking",
  SAVE_MANAGE_BOOKING: "manageBooking/saveManageBooking",
  GET_STATUS_FILTER: "manageBooking/getStatusFilter",
  GET_AMENITY_MASTER: "amenityMaster/getAmenityMaster",
  SAVE_AMENITY_MASTER: "amenityMaster/saveAmenityMaster",
  GET_KEY_MASTER: "keyMaster/getKeyMaster",
  SAVE_KEY_MASTER: "keyMaster/saveKeyMaster",
  GET_ROOM_MASTER: "roomMaster/getRoomMaster",
  SAVE_ROOM_MASTER: "roomMaster/saveRoomMaster",
  GET_ROOM_CATEGORIES: "roomMaster/getRoomCategories",
  GET_DIET_MASTER: "dietMaster/getDietMaster",
  SAVE_DIET_MASTER: "dietMaster/saveDietMaster",
  GET_DIET_CATEGORIES: "dietMaster/getDietCategories",
  GET_DIET_DELETE: "dietMaster/getDelete",
  VIEW_MEALDATA: "dietMaster/viewMealData",
  GET_KEY_LIST: "roomMaster/getKeyList",
  GET_ROOM_CATEGORY: "roomCategory/getRoomCategory",
  INSERT_ROOM_CATEGORY: "roomCategory/insertRoomCategory",
  LOG_ERROR: "insertClientLog",
  USER_LOGIN: "login",
  USER_LOGOUT: "logOut",
  REFRESH_TOKEN: "refreshToken",
  GET_HOLIDAY_YEARLIST: "getYearRangeForHolidayMaster/lookUpData",
  GET_HOLIDAYLIST: "holidayMaster/getData",
  ADD_HOLIDAY: "holidayMaster/insertData",
  UPDATE_HOLIDAY: "holidayMaster/updateData",
  DELETE_HOLIDAY: "holidayMaster/deleteData",
  EXPORT_HOLIDAY_LIST: "holidayMaster/downloadData",
  IMPORT_HOLIDAY_LIST: "holidayMaster/uploadData",
  GET_STATES: "getStateData/lookUpData",
  GET_CITIES: "getCityData/lookUpData",
  GET_EMPLOYEES: "getEmployeeData/lookUpData",
  GET_STATELIST: "stateMaster/getData",
  ADD_STATE: "stateMaster/insertData",
  UPDATE_STATE: "stateMaster/updateData",
  GET_DIVISIONLIST: "divisionMaster/getData",
  ADD_DIVISION: "divisionMaster/insertData",
  UPDATE_DIVISION: "divisionMaster/updateData",
  GET_TREATMENTROOMMASTERLIST: "treatmentRoomMaster/getData",
  ADD_TREATMENTROOM: "treatmentRoomMaster/saveData",
  UPDATE_TREATMENTROOM: "treatmentRoomMaster/updateData",
  DELETE_TREATMENTROOM: "treatmentRoomMaster/deleteData",
  GET_THERAPISTLIST: "treatmentRoomMaster/getTherapistForTreatmentRoom",
  GET_LOCATIONLIST: "locationMaster/getData",
  ADD_LOCATION: "locationMaster/insertData",
  UPDATE_LOCATION: "locationMaster/updateData",
  DELETE_LOCATION: "locationMaster/deleteData",
  GET_PATIENTNAME: "treatment/getNameData",
  GET_PERSONALDETAILS: "treatment/getPdData",
  GET_DAYWISEDATE: "treatment/getDayWiseDate",
  GET_MORNINGTHERAPY: "treatment/getMorningTherapy",
  GET_DEFAULTTHERAPY: "treatment/getDefaultTherapy",
  GET_ADDITIONALTHERAPY: "treatment/getAdditionalTherapy",
  GET_DIETPLANNAME: "treatment/getDietPlanName",
  GET_EXISTINGRECORD: "treatment/getExistingRecord",
  ADD_TREATMENTSECTIONDATA: "treatment/saveTreatmentSectionDetails",
  GET_MEALTYPENAME: "treatment/getMealTypeName",
  GET_CITYLIST: "cityMaster/getData",
  ADD_CITY: "cityMaster/insertData",
  UPDATE_CITY: "cityMaster/updateData",
  GET_DESIGNATIONLIST: "designationMaster/getData",
  ADD_DESIGNATION: "designationMaster/insertData",
  UPDATE_DESIGNATION: "designationMaster/updateData",
  GET_AREALIST: "areaMaster/getData",
  ADD_AREA: "areaMaster/insertData",
  UPDATE_AREA: "areaMaster/updateData",
  GET_ROUTELIST: "routeMaster/getData",
  ASSIGN_ROUTE: "routeMaster/insertData",
  UPDATE_ASSIGNED_ROUTE: "routeMaster/updateData",
  EXPORT_ROUTE_LIST: "routeMaster/downloadData",
  IMPORT_ROUTE_LIST: "routeMaster/uploadData",
  GET_STATIC_LOOKUP: "getStaticData/lookUpData",
  GET_CHEMISTLIST: "chemistMaster/getData",
  ADD_CHEMIST: "chemistMaster/insertData",
  UPDATE_CHEMIST: "chemistMaster/updateData",
  GET_AREAS: "getAreaData/lookUpData",
  GET_DIVISIONS: "getDivisionData/lookUpData",
  GET_ALLDIVISIONS: "getAllDivisionData/lookUpData",
  GET_STOCKISTASSIGNEDDIVISION: "getStockistAssignedDivision/lookUpData",
  GET_DESIGNATIONS: "getDesignationData/lookUpData",
  GET_EMPLOYEELIST: "employeeMaster/getData",
  GET_DEVICECONFIGURATIONLIST: "deviceConfiguration/getData",
  UPDATE_DEVICECONFIGURATIONLIST: "deviceConfiguration/updateData",
  GET_USERPANELLIST: "userPanel/getData",
  UPDATE_USERPANELLIST: "userPanel/updateData",
  ADD_EMPLOYEE: "employeeMaster/insertData",
  UPDATE_EMPLOYEE: "employeeMaster/updateData",
  GET_STOCKISTLIST: "stockistMaster/getData",
  ADD_STOCKIST: "stockistMaster/insertData",
  UPDATE_STOCKIST: "stockistMaster/updateData",
  GET_ITEMLIST: "itemMaster/getData",
  ADD_ITEM: "itemMaster/insertData",
  UPDATE_ITEM: "itemMaster/updateData",
  EXPORT_ITEM_LIST: "itemMaster/downloadData",
  IMPORT_ITEM_LIST: "itemMaster/uploadData",
  GET_COUNTRIES: "getCountryData/lookUpData",
  CHANGE_PASSWORD: "changePassword",
  FORGOT_PASSWORD: "forgotPassword",
  GET_ROUTES: "getRouteData/lookUpData",
  GET_SCHEMELIST: "schemeMaster/getData",
  GET_AVAILABLE_ITEMLIST: "getAvailableItemsForSchemeData/lookUpData",
  ADD_SCHEME: "schemeMaster/insertData",
  UPDATE_SCHEME: "schemeMaster/updateData",
  UPDATE_SCHEME_ITEMS: "schemeMaster/updateSchemeWiseItem",
  GET_CATEGORIES: "getCategoryData/lookUpData",
  GET_ITEM_PRICELIST: "itemPriceMaster/getData",
  ADD_ITEMPRICE: "itemPriceMaster/insertData",
  GET_ITEMPRICE_EXPORTDATES: "itemPriceMaster/getEffectiveExportDates",
  GET_LEAVELIST: "leaveMaster/getData",
  ADD_LEAVE: "leaveMaster/insertData",
  DELETE_LEAVE: "leaveMaster/deleteData",
  UPDATE_LEAVE: "leaveMaster/updateData",
  EXPORT_ITEM_PRICELIST: "itemPriceMaster/downloadData",
  GET_SL_TOURPLAN: "slTourPlan/getData",
  SAVE_SL_TOURPLAN: "slTourPlan/insertData",
  GET_SL_WORKINGWITH: "slTourPlan/getData",
  SAVE_REJECT_SL_TOURPLAN: "tourPlanApproval/updateData",
  SAVE_REJECT_MANAGER_TOURPLAN: "tourPlanApproval/updateData",
  GET_MANAGER_TOURPLAN: "managerTourPlan/getData",
  SAVE_MANAGER_TOURPLAN: "managerTourPlan/insertData",
  GET_MANAGER_WORKINGWITH: "slTourPlan/getData",
  GET_TOURPLAN_MONTHYEARLIST: "getMonthYearRangeForTourPlan/lookUpData",
  GET_SL_OR_MANAGER_LIST: "getSLOrManagerListByEmployeeId/lookUpData",
  GET_SUBORDINATES: "getSubordinatesByEmployeeId/lookUpData",
  // GET_ROUTES_OF_EMPLOYEE: "getRoutesByEmployeeId/lookUpData",
  GET_FINANCIAL_MONTHYEARLIST:
    "getMonthYearRangeForCurrentFinancialYear/lookUpData",
  GET_MONTHYEAR_RANGE_LIST: "getMonthYearRangeForGivenRange/lookUpData",
  GET_TP_APPROVAL_LIST: "tourPlanApproval/getData",
  UPDATE_TP_STATUS: "tourPlanApproval/updateData",
  ASSIGN_CHEMIST_TO_ROUTE: "chemistMaster/updateRoute",
  GET_DCR_CALENDAR_DATA: "dcr/getData",
  GET_DCR_PREVIEW_DATA: "dcr/previewData",
  UNLOCK_DCR_REQUEST: "unlockDCR/insertData",
  GET_UNLOCK_DCR_DATA: "unlockDCR/getData",
  UPDATE_UNLOCK_DCR: "unlockDCR/updateData",
  GET_POB_DATA: "getChemistList/getData",
  SAVE_POB_DATA: "pob/saveData",
  GET_EXPENSE_BYROUTE: "expense/getData",
  SAVE_EXPENSE: "expense/insertData",
  GET_EXPENSE_CONFIG: "expenseConfigurationMaster/getData",
  SAVE_EXPENSE_CONFIG: "expenseConfigurationMaster/updateData",
  GET_BROADCAST_MOBILE_NEWS_LIST: "broadcastMobileNewsMaster/getData",
  ADD_BROADCAST_MOBILE_NEWS_LIST: "broadcastMobileNewsMaster/insertData",
  UPDATE_BROADCAST_MOBILE_NEWS_LIST: "broadcastMobileNewsMaster/updateData",
  GET_EXPENSE_APPROVAL_LIST: "expenseApproval/getData",
  GET_EXPENSE_APPROVAL_LIST_OF_EMPLOYEE: "expenseApproval/getDataByEmployeeId",
  UPDATE_EXPENSE_APPROVAL: "expenseApproval/updateData",
  GET_STOCKISTLIST_OF_STATE_EMPLOYEE: "stockistEmployeeMaster/getData",
  ASSIGN_STOCKIST_TO_EMPLOYEE: "stockistEmployeeMaster/insertData",
  MERGE_ROUTES: "mergeRoute/insertData",
  GET_USERPROFILE_DATA: "viewProfile/getData",
  GET_DASHBOARD_SUMMARY_DATA: "dashboardPobProductiveMonthlyCall/getData",
  GET_DASHBOARD_CHEMIST_BIRTHDAY_LIST: "dashboardChemistBirthday/getData",
  GET_DASHBOARD_COUNT_DATA: "dashboardCountData/getData",
  GET_MONTHLYSTATUS_ORDERCOUNT: "monthlyStatus/getData",
  GET_LEAVE_REPORT: "leaveReport/getData",
  GET_EXPENSE_REPORT_LIST: "tpVsAutoVsDCRExpenseReport/getMasterData",
  GET_EXPENSE_REPORT_COMPARISON_DATA: "tpVsAutoVsDCRExpenseReport/getData",
  GET_NOTIFICATIONS: "notificationInfo/getData",
  TRANSFER_ROUTES_TO_EMPLOYEE: "transferRoutesToEmployee/updateData",
  ADD_NOTIFICATION: "notificationInfo/insertData",
  SEND_SMS: "sendSms",
  GET_SMS_CODE: "gpsLocationHistoryReport/getSMSCode",
  GET_SMS_MESSAGE: "gpsLocationHistoryReport/getSMSMessage",
  CHECK_PENDING_LEAVE_APPROVALS: "isLeaveApprovalPending/getData",
  GET_CHEMIST_CUMULATIVE_PROD_CALLS_LIST:
    "cululativeProductiveCallReport/getData",
  GET_GPS_TRACK_DATA: "gpsLocationHistoryReport/getData",
  GET_GPS_LOCATION_HISTORY_DATA: "gpsLocationHistoryReport/getDataById",
  MANAGE_DCR: "manageDCR",
  GET_ADD_DCR_ROUTES: "getRoutesForAddDCR/lookUpData",
  GET_MANAGER_VS_TEAM_DATA: "managerVsTeamReport/getData",
  GET_NOTIFICATION_COUNT: "notificationInfo/getCount",
  GET_TP_VS_ACTUAL_DATA: "tpVsActualRouteReport/getData",
  GET_CHEMIST_VISITS_DATA: "chemistVisitsReport/getData",
  GET_REGISTRATION_APPROVAL_DATA: "userRegistration/getData",
  UPDATE_REGISTRATION_REQ: "userRegistration/updateData",
  GET_SCHEMES: "schemeMaster/getSchemeLookupData",
  GET_REWARDLIST: "rewardMaster/getDataBySchemeId",
  ADD_REWARD: "rewardMaster/insertData",
  UPDATE_REWARD: "rewardMaster/updateData",
  SAVE_ADVERTISE_IMAGES: "advertise/insertData",
  GET_ADVERTISE_IMAGES: "advertise/getData",
  GET_INVOICE_LIST: "invoiceMaster/getData",
  UPDATE_INVOICE: "invoiceMaster/updateData",
  CHECK_DUPLICATE_INVOICE: "invoiceMaster/checkDuplicate",
  UPDATE_RETURN_INVOICE: "invoiceMaster/updateReturnData",
  APPROVE_RETURN_INVOICE: "invoiceMaster/updateReturnStatusData",
  GET_STOCKIST: "getStockistData/lookUpData",
  GET_SUPERSTOCKIST: "getSuperStockistData/lookUpData",
  GET_ORDER_LIST: "order/getDataByStateCityStatus",
  GET_ORDERDATA_BYID: "order/getDataByOrderId",
  UPDATE_ORDER: "order/updateStockistData",
  GET_REDEMPTION_LIST: "redeemRequest/getData",
  UPDATE_REDEMPTION: "redeemRequest/updateData",
  GET_REDEMPTION_APPROVALMESSAGE: "redeemRequest/getMessageData",
  UPDATE_POINTS: "updatePoints/updateData",
  GET_EMPROUTELIST: "empRoute/getRouteData",
  DOWNLOAD_EMPROUTELIST: "empRoute/downloadRouteData",
  GET_ATTENDANCE: "attendanceReport/getData",
  GET_TARGET: "targetMaster/getData",
  INSERT_TARGET: "targetMaster/insertData",
  GET_WORKFLOW: "workFlow/lookUpData",
  GET_MATCHING_CHEMIST_DATA: "userRegistration/getMatchingChemistData",
  GET_MOB_OWNER_NAME: "employeeMaster/getMobileOwnerName",
  GET_CHEMIST_PROFILE_LIST: "chemistProfileUpdate/getListData",
  GET_CHEMIST_PROFILE_DATA: "chemistProfileUpdate/getData",
  UPDATE_CHEMIST_PROFILE: "chemistProfileUpdate/updateData",
  GET_LOOKUP_ROUTES: "routeMaster/routeLookupData",
  GET_MONTHLY_EXPENSE_SUMMARY_REPORT_Data: "monthlyExpenseSummary/getData",
  GET_SERIESLIST: "videoSeriesMaster/getSeriesData",
  ADD_SERIES: "videoSeriesMaster/saveSeriesData",
  GET_DOCUMENTTYPELIST: "documentType/getData",
  ADD_DOCUMENTTYPE: "documentType/saveData",
  UPDATE_DOCUMENTTYPE: "documentType/updateData",
  GET_VIDEOLIST: "videoMaster/getVideos",
  ADD_VIDEOSERIES: "videoMaster/saveVideo",
  GET_SERIESDATA: "videoMaster/getSeriesData",
  GET_TANDC: "tandc/getData",
  SAVE_TANDC: "tandc/saveData",
  DCR_PREVIEW_ASYNC: "dcr/previewDCRData",
  GET_GPS_TRACK_DATA_BY_ATETIMEANDEMPLOYEE:
    "gpsTracer/getDataByDateTimeAndEmployee",
  GET_VIDEO_SUMMARY_REPORT_DATA: "videoSummary/getVideoSummary",
  GET_VIDEO_SUMMARY_DETAILS_DATA: "videoSummary/getVideoCommentSummary",
  DCR_CALENDER_ASYNC: "dcr/getCalendarDataAsync",
  GET_DASHBOARD_STATEWISE_COUNT_DATA:
    "dashboardCountData/getDataStateWiseCount",
  GET_DASHBOARD_STATEWISE_DATA: "dashboardCountData/getDataStateWiseData",
  GET_EXPENSE_APPROVAL_LIST_OF_EMPLOYEE_ASYNC: "expenseApproval/getAsyncData",
  GET_FEATURE_DATA: "feature/getData",
  SAVE_FEATURE_DATA: "feature/saveData",
  GET_SELFIE_DATA: "selfie/getData",
  SAVE_SELFIE_DATA: "selfie/saveData",
  GET_SURVEY_DATA: "surveyMaster/getSurveyList",
  SAVE_SURVEY_DATA: "surveyMaster/saveSurveyData",
  GET_SURVEYQUESTION_DATA: "surveyMaster/getSurveyQuestionList",
  GET_ANSWERGROUP_DATA: "surveyMaster/getAnswerGroupList",
  SAVE_SURVEYQUESTION_DATA: "surveyMaster/saveSurveyQuestion",
  DELETE_SURVEYQUESTION_DATA: "surveyMaster/deleteSurveyQuestion",
  SAVE_SURVEYCOPY_DATA: "surveyMaster/saveSurveyCopy",
  GET_AWS_FILEUPLOAD_URL: "aws/getFileUploadURL",
  GET_QUESTION_TYPE: "answerOption/getData",
  SAVE_QUESTION_TYPE: "answerOption/saveData",
  SEND_NOTIFICATION: "feature/sendNotification",
  SEND_FEATURE_SMS: "feature/sendSMS",
  GET_SURVEYREPORT_DATA: "surveyReport/getSurveyData",
  GET_SURVEYCHEMIST_DATA: "surveyReport/getChemistData",
  GET_ACTIVESURVEY_DATA: "surveyReport/getActiveSurveyList",
  GET_POINTSCONFIG_DATA: "pointConfig/getData",
  SAVE_POINTSCONFIG_DATA: "pointConfig/updatePointsConfigData",
  GET_CUSTOME_RORDER_DATA: "customerOrder/getDataByDate",
  GET_CUSTOME_RORDER_DATA_BYID: "customerOrder/getDataByOrderId",
  UPDATE_CUSTOME_RORDER_DATA: "customerOrder/updateStockistData",
  GET_MYORDER_LIST: "myOrder/getData",
  GET_MYORDER_ITEMPRICE: "myOrder/getItemData",
  SAVE_MYORDER: "myOrder/saveMyOrder",
  GET_MENUROLE_LIST: "menuRole/getData",
  REFRESH_MENU_ITEM: "menuRole/refreshMenuItem",
  SAVE_MENUROLE_DATA: "menuRole/saveMenuRoleData",
  GET_DEFAULT_SECONDARY: "secondaryPoint/getDefaultSecondary",
  UPDATE_DEFAULT_SECONDARY: "secondaryPoint/updateDefaultSecondary",
  UPDATE_DEFAULTALL_SECONDARY: "secondaryPoint/updateAllDefaultSecondary",
  GET_CLAIMREWARD: "claimReward/getData",
  GET_ITEMWISESALES: "itemWiseSales/getData",
  GET_TOPCUSTOMER: "topCustomer/getData",
  GET_PRIMARYPURCHASELIST: "primaryPurchase/getData",
  IMPORT_PRIMARYPURCHASE_LIST: "primaryPurchase/uploadData",
  SAVE_PRIMARYPURCHASE: "primaryPurchase/saveData",
  GET_GPSSMSTRACK: "gpsSmsTrack/getData",
  GET_PRIMARYVSSECONDARY: "primaryVsSecondary/getData",
  GET_SMARTSETUAPP: "smartSetuApp/getData",
  GET_PRIMARYVSCLAIM: "primaryVsClaim/getData",
  GET_EMPLOYEEREFMAPPING: "employeeRefMapping/getData",
  GET_QRLIST: "qrMaster/getData",
  ADD_QR: "qrMaster/insertData",
  UPDATE_QR: "qrMaster/updateData",
  DELETE_QR: "qrMaster/deleteData",
  GENERATE_QR: "qrMaster/generateQRCodeData",
  PRINTDOWNLOAD_QR: "qrMaster/printDownloadQRData",
  GET_QRPRINTHISTORY: "qrMaster/getQRPrintHistory",
  GET_INVOICEITEMDATA: "invoiceMaster/getInvoiceItemData",
  GET_DEPO_LIST: "getDepotData/lookUpData",
  GET_CLOSING_STOCK_LIST: "closingStock/getData",
  GET_MONTHLY_SALES_DATA: "sales/getData",
  READ_FTP_FILES: "connectFTP/getData",
  GET_STOCKIST_FILTER_LIST: "stockistEmployeeMaster/getAssignedStockist",
  GET_OUTSTANDING_REPORT: "outstanding/getData",
  GET_FTP_DIVISION_LIST: "getFTPDivisionData/lookUpData",
  GET_GUESTLIST: "guestMaster/getData",
  ADD_GUEST: "guestMaster/insertData",
  UPDATE_GUEST: "guestMaster/updateData",
  GET_DISEASE_MASTER: "diseaseMaster/getDiseaseMaster",
  SAVE_DISEASE_MASTER: "diseaseMaster/saveDiseaseMaster",
  DELETE_DISEASE_MASTER: "diseaseMaster/deleteDiseaseMaster",
  GET_TREATMENT_MASTER: "treatmentMaster/getTreatmentMaster",
  SAVE_TREATMENT_MASTER: "treatmentMaster/insertData",
  EDIT_TREATMENT_MASTER: "treatmentMaster/updateData",
  DELETE_TREATMENT_MASTER: "treatmentMaster/deleteData",
  GET_DISEASE_FOR_TREATMENT_MASTER: "treatmentMaster/getDiseaseMasterfortreatment",
  GET_DIETLIST_MASTER: "treatment/getDietPlan",
  GET_HEALTHLIST: "treatment/getDisease",
  GET_TREATMENTTEMPLATE_CATEGORIES: "treatmentPlanMaster/getTreatmentTemplateCategories",
  GET_TREATMENTLIST_DATA: "treatmentPlanMaster/getTreatmentList",
  GET_DIETLIST_DATA: "treatmentPlanMaster/getDietList",
  ADD_TREATMENTPLAN: "treatmentPlanMaster/insertDayWisePlanData",
  GET_DISEASE_COMMENT: "treatment/getComments",
  GET_DISEASEDATA: "treatment/getDisease",
  GET_DISEASELIST: "treatment/getDisease",
  SAVE_DISEASELIST: "treatment/insertDisease",
  UPDATE_DISEASEDATA: "treatment/updateDiseaseData",
  GET_APPROVAL_LEAVE: "leaveApproval/getApprovalLeave",
  UPDATE_APPROVAL_LEAVE: "leaveApproval/updateApprovalLeave",
  GET_DISEASE_NAME: "treatementtempletemaster/getdietname",
  GET_TREATMENT_NAME: "treatementtempletemaster/getTreatment",
  SAVE_TEMPLETE_NAME: "treatementtempletemaster/inserttreatmentdata",
  GET_DISEASELIST: "treatementtempletemaster/getdiseaselist",
  GET_TEMPLETEDISEASE: "treatementtempletemaster/gettempletediseaselist",
  DELETE_TEMPLETE: "treatementtempletemaster/deletetemplete",
  UPDATE_TEMPLETE: "treatementtempletemaster/updatetemplete",
  GET_DAILYTHERAPY: "dailyTherapyMaster/getData",
  GET_DAILYTHERAPY_TYPENAME: "dailyTherapyMaster/getTypeName",
  GET_DAILYTHERAPY_UPDATE: "dailyTherapyMaster/updateData",
  GET_DAILYTHERAPY_SLOT: "dailyTherapyMaster/getSlot",
  GET_TEMPLATENAMELIST: "treatementtempletemaster/getTreatmentdetail",
  UPDATE_DIET: "dietMaster/updateDietMaster",
  GET_ROOMRATETIME: "RoomRateMaster/getTime",
  GET_ROOMFILTER: "RoomRateMaster/datefilter",
  GET_LISTALLCATEGORYNAME: "RoomRateMaster/listallcategoryname",
  GET_LISTDAYS: "RoomRateMaster/listdays",
  SAVE_ROOMRATE: "RoomRateMaster/saveroomRate",
  UPDATE_ROOMRATE: "RoomRateMaster/updateroomRate",
  GET_OCCUPANCY: "memberShipMaster/getOccupancy",
  GET_THERAPYTYPE: "therapyTypeMaster/getTherapyType",
  GET_DISEASE_NAME: "treatementtempletemaster/getdietname",
  GET_TREATMENT_NAME: "treatementtempletemaster/getTreatment",
  SAVE_TEMPLETE_NAME: "treatementtempletemaster/inserttreatmentdata",
  GET_DISEASELIST: "treatementtempletemaster/getdiseaselist",
  GET_TEMPLETEDISEASE: "treatementtempletemaster/gettempletediseaselist",
  DELETE_TEMPLETE: "treatementtempletemaster/deletetemplete",
  UPDATE_TEMPLETE: "treatementtempletemaster/updatetemplete",
  GET_DAILYTHERAPY: "dailyTherapyMaster/getData",
  GET_DAILYTHERAPY_TYPENAME: "dailyTherapyMaster/getTypeName",
  GET_DAILYTHERAPY_UPDATE: "dailyTherapyMaster/updateData",
  GET_DAILYTHERAPY_SLOT: "dailyTherapyMaster/getSlot",
  GET_TEMPLATENAMELIST: "treatementtempletemaster/getTreatmentdetail",
  UPDATE_DIET: "dietMaster/updateDietMaster",
  GET_ROOMRATETIME: "RoomRateMaster/getTime",
  GET_ROOMFILTER: "RoomRateMaster/datefilter",
  GET_LISTALLCATEGORYNAME: "RoomRateMaster/listallcategoryname",
  GET_LISTDAYS: "RoomRateMaster/listdays",
  SAVE_ROOMRATE: "RoomRateMaster/saveroomRate",
  GET_OCCUPANCY: "memberShipMaster/getOccupancy",
  GET_THERAPYTYPE: "therapyTypeMaster/getTherapyType",
  SAVE_THERAPYTYPE: "therapyTypeMaster/saveTherapyType",
  DELETE_THERAPYTYPE: "therapyTypeMaster/deleteTherapyType",
  GET_THERAPYSLOT: "therapySlotMaster/getTherapySlot",
  SAVE_THERAPYSLOT: "therapySlotMaster/saveTherapySlot",
  DELETE_THERAPYSLOT: "therapySlotMaster/deleteTherapySlot",
  GET_THERAPY: "therapySlotMaster/getTherapy",
  GET_MEMBERSHIP: "memberShipMaster/getMemberShip",
  GET_DAYS: "memberShipMaster/getDaysMemberShip",
  ADD_MEMBERSHIP : "memberShipMaster/insertData",
  UPDATE_MEMBERSHIP:"memberShipMaster/updateData",
  DELETE_MEMBERSHIP:"memberShipMaster/deleteData",
  GET_MEMBERSHIP_EFFECTIVEDATE: "memberShipMaster/getEffectiveDate",
  GET_LATESTGUEST: "manageBooking/getLatestGuest",
  GET_ROOMLIST: "manageBooking/getRoomList",
  GET_ROOMSTATUS: "manageBooking/getRoomStatus",
  GET_DEFAULTROOMSTATUS: "manageBooking/getDefaultRoomStatus",
  
  SINGLE_EMPLOYEE: "employeeMaster/getSingleEmployeeData",
  GET_MEALEDITDAY: "mealTemplate/getMealEditDay",
  GET_EFFECTIVEDATEFILTER: "mealTemplate/getEffectiveDateFilter",
  GET_MEALTEMPLATELIST: "mealTemplate/getMealTemplateList",
  GET_EXISTINGMEALDATA: "mealTemplate/getExistingMealData",
  ADD_MEALTEMPLATE: "mealTemplate/saveMealTemplateData",
  UPDATE_MEALTEMPLATEATA: "mealTemplate/updateMealTemplateData",
  DELETE_MEALTEMPLATE: "mealTemplate/deleteMealTemplateData",
  
  guestUploadFile_getData: "guestUploadFile/getUploadFileData",
  guestUploadFile_downloadFile: "guestUploadFile/downloadFile",
  DELETE_ROOMRATE: "RoomRateMaster/deleteroomRate",
  guestUploadFile_getData: "guestUploadFile/getUploadFileData",
  GET_EXISTINGDATAONEFFEDATEWISE: "mealTemplate/getExistingDataOnEffeDateWise",
  GET_EFFECTIVEDATE: "dateWiseMealTemplate/getEffectiveDate",
  GET_DATEWISEMEALTEMPLATELIST: "dateWiseMealTemplate/getDateWiseMealTemplateList",
  GET_EXISTINGDATEWISEMEALTEMPLATELIST: "dateWiseMealTemplate/getExistingDateWiseMealTemplateList",
  GET_DATEWISEMEALTEMPLATEEXISTINGDATA: "dateWiseMealTemplate/getDateWiseMealTemplateExistingData",
  ADD_DATEWISEMEALTEMPLATE: "dateWiseMealTemplate/saveDateWiseMealTemplateData",
  UPDATE_DATEWISEMEALTEMPLATE: "dateWiseMealTemplate/updateDateWiseMealTemplateData",
  DELETE_DATEWISEMEALTEMPLATE: "dateWiseMealTemplate/deleteDateWiseMealTemplateData",
	GET_DEFAULTROOMCATEGORY: "manageBooking/getDefaultRoomCategory",
  guestUploadFile_getData:"guestUploadFile/getUploadFileData",
  guestUploadFile_downloadFile:"guestUploadFile/downloadFile",
  DELETE_ROOMRATE:"RoomRateMaster/deleteroomRate",
  manageBooking_getbookingData:"manageBooking/getbookingData",
  manageBooking_getGuestBookingDetails:"manageBooking/getGuestBookingDetails",
  manageBooking_getRoomAssignDetails:"manageBooking/getRoomAssignDetails",
  manageBooking_updateManageBooking:"manageBooking/updateManageBooking",
  manageBooking_deleteManageBooking:"manageBooking/deleteBooking",
  manageBooking_checkedOutPerticularRoom:"manageBooking/checkedOutPerticularRoom",
};
const PUBLIC_APIS = ["login", "forgotPassword", "treatment/updateDisease", "diseaseMaster/getDiseaseMaster"];
const STATIC_LOOKUP_CODES = {
  ROUTE_TYPES: "RouteTypes",
  EMPLOYEE_STATUS: "EmployeeStatus",
  UOM_VALUES: "UOMValues",
  SCHEME_UOM: "SchemeUOM",
  LEAVE_CATEGORY: "LeaveCategory",
  LEAVE_TYPES: "LeaveTypes",
  LEAVE_STATUS: "LeaveStatus",
  GPS_CALLS_FILTER: "CallsType",
  INVOICE_STATUS: "InvoiceStatus",
  ORDER_STATUS: "OrderStatus",
  REG_REQ_STATUS: "StockistChemistRequestStatus",
  CHEM_PROF_UPDATE_REQ_STATUS: "ChemistProfileUpdateStatus",
  DocumentTypeGroup: "DocumentTypeGroup",
  APP_INDICATOR: "ApplicationIndicator",
  QUESTION_TYPE: "QuestionType",
  SELFIE_APPROVAL: "SelfieApproval",
  ROOM_STATUS: "RoomStatus",
};

module.exports = {
  BASE_URL,
  GOOGLE_API_KEY,
  API,
  PUBLIC_APIS,
  STATIC_LOOKUP_CODES,
};
